INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Persa', 'Irán', 'Mediano', 4.5, 'Gato con pelo largo y cara plana. Muy tranquilo y cariñoso.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Siamés', 'Tailandia', 'Mediano', 3.5, 'Gato elegante y delgado con ojos azules y carácter vocal.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Maine Coon', 'Estados Unidos', 'Grande', 7.0, 'Gato grande y robusto con una personalidad amistosa.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Bengalí', 'Estados Unidos', 'Mediano', 5.0, 'Gato con apariencia salvaje y manchas en su pelaje. Muy activo.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Sphynx', 'Canadá', 'Mediano', 4.0, 'Gato sin pelo, conocido por su piel arrugada y personalidad afectuosa.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Abisinio', 'Etiopía', 'Mediano', 4.0, 'Gato atlético y enérgico con pelaje corto y suave.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Ragdoll', 'Estados Unidos', 'Grande', 6.5, 'Gato grande y dócil, conocido por su comportamiento relajado y ojos azules.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Birmano', 'Birmania', 'Mediano', 5.0, 'Gato de pelaje semilargo y carácter amigable.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Scottish Fold', 'Escocia', 'Mediano', 4.5, 'Gato con orejas dobladas hacia adelante y personalidad tranquila.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Devon Rex', 'Reino Unido', 'Mediano', 3.5, 'Gato con pelaje rizado y gran inteligencia, muy activo.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Chartreux', 'Francia', 'Mediano', 4.5, 'Gato con pelaje azul-grisáceo y ojos cobrizos, tranquilo y afectuoso.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('British Shorthair', 'Reino Unido', 'Mediano', 5.5, 'Gato robusto con pelaje denso y carácter calmado.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Norwegian Forest', 'Noruega', 'Grande', 6.0, 'Gato grande y robusto, adaptado a climas fríos con pelaje espeso.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Siberiano', 'Rusia', 'Grande', 6.5, 'Gato grande y musculoso con pelaje grueso, adaptado a climas fríos.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Cornish Rex', 'Reino Unido', 'Mediano', 3.5, 'Gato con pelaje corto y rizado, muy activo y sociable.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Oriental', 'Tailandia', 'Mediano', 4.0, 'Gato elegante con cuerpo delgado y personalidad extrovertida.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Balinese', 'Estados Unidos', 'Mediano', 4.5, 'Gato similar al siamés pero con pelaje semilargo, muy vocal y cariñoso.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Himalayo', 'Estados Unidos', 'Mediano', 5.0, 'Gato con pelaje largo y ojos azules, mezcla de persa y siamés.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Somalí', 'Estados Unidos', 'Mediano', 4.0, 'Gato de pelaje semilargo y coloración similar al abisinio, activo y curioso.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Tonkinés', 'Canadá', 'Mediano', 4.5, 'Gato cruzado entre siamés y burmés, muy social y juguetón.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Manx', 'Isla de Man', 'Mediano', 4.5, 'Gato sin cola o con cola muy corta, robusto y afectuoso.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Ocicat', 'Estados Unidos', 'Mediano', 5.0, 'Gato con apariencia de ocelote, muy activo y social.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Russian Blue', 'Rusia', 'Mediano', 4.5, 'Gato con pelaje corto y azul-grisáceo, ojos verdes y carácter tranquilo.')
INSERT INTO Raza (nombre, origen, tamanho, peso_promedio, descripcion) VALUES ('Burmés', 'Myanmar', 'Mediano', 4.5, 'Gato musculoso con pelaje corto y brillante, muy cariñoso y juguetón.')


INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Keo', 1, '2023-07-15')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Ruby', 2, '2024-07-15')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Nala', 3, '2003-07-15')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Pepe', 4, '2022-03-25')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Keo', 5, '2023-07-15')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Ruby', 6, '2024-07-15')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Nala', 7, '2003-07-15')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Pepe', 8, '2022-03-25')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Keo', 9, '2023-07-15')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Ruby', 12, '2024-07-15')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Nala', 13, '2003-07-15')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Pepe', 14, '2022-03-25')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Keo', 11, '2023-07-15')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Ruby', 12, '2024-07-15')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Nala', 13, '2003-07-15')
INSERT INTO Gato (nombre, raza, fecha_nacimiento) VALUES ('Pepe', 14, '2022-03-25')

